// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonAPI_Second.Persistence;

#nullable disable

namespace PersonAPI_Second.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730135646_RemovedAddPersonDto")]
    partial class RemovedAddPersonDto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonAPI_Second.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("133d523e-e57b-4865-a8d2-c8dccc5fe048"),
                            Address = "100 Charming Avenue",
                            DOB = new DateOnly(2005, 4, 16),
                            FirstName = "Casper",
                            LastName = "Mohabaty"
                        },
                        new
                        {
                            Id = new Guid("b861dd22-5c9e-4e6e-baf5-8784b979a8c3"),
                            Address = "Wazzaaaaaa",
                            DOB = new DateOnly(2000, 1, 1),
                            FirstName = "Flerbert",
                            LastName = "Schminkledorf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
